

let data = 
     
    {
        "one":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:"https://www.youtube.com/watch?v=14uOL_dUcJ4&list=PLiPy3hM238v5yisaZMgLKrYo1beRoN-WF"
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Two":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Three":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Four":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Five":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Six":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Seven":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Eight":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Nine":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Ten":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Eleven":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ],
        "Twelve":[
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
            {
                class:"one",
                SubjectName:"Maths",
                Pdflink:"",
                YoutubeLink:""
            },
        ]
    }
    















]